Revert "Use .ts eslint.config directly instead of building it to .js"
This reverts commit 1542f2737cadf31de0b2356d5bf9265b1bc39558. 

Task [#5]

diff --git a/git-hooks/pre-commit b/git-hooks/pre-commit
--- a/git-hooks/pre-commit
+++ b/git-hooks/pre-commit
@@ -68,6 +68,19 @@ function validate_ts() {
 }
 validate_ts &
 
+function js_build() {
+    echo "${YELLOW}[pre-commit]${BLUE} Running \`yarn build\`... ${WHITE}"
+    OUTPUT=$(yarn build 2>&1)
+    if [[ $? != 0 ]]; then
+        echo
+        echo "${BLUE}JS Build failed."
+        echo "${RED}$OUTPUT"
+        exit_reset_colors
+    fi
+    echo "${YELLOW}[pre-commit]${GREEN} Yarn Build Completed!${RESET_COLOR}"
+}
+js_build &
+
 # Go through each background task
 # If it sent exit code 1, it failed and the result from `wait` will be false.
 FAIL=0
